### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by fepegar**

### CODE REVIEW

**Comment by johnstairs** [comment]
Thanks @fepegar! I'm just trying to work through permissions issues trying to run the GitHub actions checks on a fork (this is our first such PR).

**Comment by fepegar** [comment]
I'll keep an eye open for those changes! I didn't know the `azure/login` action and it sounds like something we'll also need for our CI anyway.

**Comment by johnstairs** [comment]
This ended up being much more involved than I expected. See #91 if interested.

**Review by johnstairs — APPROVED** [review]

**Comment by fepegar** [comment]
I'm glad my 6-character-diff PR somehow helped fixing something actually important!

**Pull request merged**
